# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9bd22008ec2bdf5c5a6fa1ffdfb34475ef0f332c055220c527c879494213739677558d0f5177a7c9a8ce8a6cbb0a95ea671c48419792bc0e0839827a28a0605

test:
  secret_key_base: f76eb3a937512af76b201cec3f87c8c4a7e277a66679185c9bdcd296bfb1db510e33d8fef5ab99c65e1183a5f3b7ece5f3ac3ce2fd797076519955bfc11fb646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
